name: MacOS build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install \
            cmake \
            curl \
            gtkmm3 \
            ninja

      # Workaround for now, we create our own features.h file (macos image either is missing this file, or some include folder is missing during the build)
      - name: Add `features.h`
        run: |
          cat >> src/features.h << EOF
          #pragma once
          /*** @file features.h*
          * @brief Synonym for `<sys/cdefs.h>` for source compatibility with glibc.
          * */
          #include <sys/cdefs.h>
          EOF

      - name: Build
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DDOXYGEN:BOOL=FALSE ..
          ninja

      - uses: actions/upload-artifact@v2
        with:
          name: macOS-binary
          path: build/src/libreweb-browser
      
      # TODO: Packaging using CPack and PackageMaker

      #xcodebuild \
      # -project "libreweb-browser.xcodeproj" \
      #    -scheme libreweb-browser \
      #    -configuration Debug
